### ISSUE TITLE
"Database connection [tenant] not configured" error and trait SerializesModels

### ISSUE THREAD

**Issue by albertosgz** [tenancy/tenancy#181]
Hi. I use to use the Hyn/Tenancy one, and I switch to TT since it looks very promising! Thank so much for all your work and dedication.

__Description__

I have a problem creating an event with SerializesModels trait. If I remove it, I can workaround with the error, but I can't get the user to send the Notification.

I define an event UserCreated when a user is created, which belongs to a Tenant.

```php
class User extends Authenticatable implements HasLocalePreference
{
    use Notifiable;
    use OnTenant;
    ...

    protected $dispatchesEvents = [
        'created' => UserCreated::class,
    ];
    ...
}

class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        ...
        UserCreated::class => [
            SendUserCreatedNotification::class,
        ],
    ];
}

class UserCreated
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }
}
```

The SendUserCreatedNotification is a listener which listens to UserCreated event and is queued.

```php
class SendUserCreatedNotification implements ShouldQueue
{
    use SerializesModels;

    protected $user;

    /** @var Customer $tenant */
    public $tenant;

    public function __construct(User $user)
    {
        logger('[SendUserCreatedNotification::__construct] 1 ' . $user);
        $this->user = $user;
    }

    public function handle()
    {
        logger('[SendUserCreatedNotification] 2 user: '.$this->user);
        $this->user->notifyNow(new UserCreation());
    }
}
```

But it looks there is an error in the deserializing the model.
May it be is trying to access to the database in order to get the User before setting the Tenant?

This is the queue identification function (just a copy from web):
```php
    public function tenantIdentificationByQueue(Processing $event): ?Tenant
    {
        if ($event->tenant) {
            return $event->tenant;
        }

        if ($event->tenant_key && $event->tenant_identifier === $this->getTenantIdentifier()) {
            $tenant = $this->newQuery()
                ->where($this->getTenantKeyName(), $event->tenant_key)
                ->first();
            return $tenant;
        }

        return null;
    }
```

I upgrade all packages to version 1.0.1
In my tests a write a log in the facade of the library to check if it is fired, and I confirm it.

__Actual behavior__

An exception `Database connection [tenant] not configured` is launched.

__Expected behavior__

Continue the work of the notification.

---
__Information__

- tenancy/tenancy version: 101
- laravel version: 7.20.0
- database driver and version: tenancy/db-driver-mysql v1.0.1
- webserver software and version: nginx/1.17.6
- php version: 7.3

---

__tenancy.php config__

I don't have.

---

__Error log__

```text
[2020-07-15 15:50:17] local.DEBUG: [SendUserCreatedNotification::__construct] 1 []
[2020-07-15 15:50:18] local.ERROR: Database connection [tenant] not configured. {"exception":"[object] (InvalidArgumentException(code: 0): Database connection [tenant] not configured. at /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:152)
[stacktrace]
#0 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(115): Illuminate\\Database\\DatabaseManager->configuration('tenant')
#1 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(86): Illuminate\\Database\\DatabaseManager->makeConnection('tenant')
#2 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1342): Illuminate\\Database\\DatabaseManager->connection('tenant')
#3 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1308): Illuminate\\Database\\Eloquent\\Model::resolveConnection('tenant')
#4 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1114): Illuminate\\Database\\Eloquent\\Model->getConnection()
#5 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1031): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()
#6 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1067): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#7 /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1093): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#8 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(114): Illuminate\\Database\\Eloquent\\Model->newQueryForRestoration(46)
#9 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(101): App\\Events\\UserCreated->getQueryForModelRestoration(Object(App\\Models\\User), 46)
#10 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(57): App\\Events\\UserCreated->restoreModel(Object(Illuminate\\Contracts\\Database\\ModelIdentifier))
#11 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(45): App\\Events\\UserCreated->getRestoredPropertyValue(Object(Illuminate\\Contracts\\Database\\ModelIdentifier))
#12 [internal function]: App\\Events\\UserCreated->__wakeup()
#13 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(171): unserialize('O:36:\"Illuminat...')
#14 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(213): Illuminate\\Queue\\CallQueuedHandler->failed(Array, Object(InvalidArgumentException))
#15 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(192): Illuminate\\Queue\\Jobs\\Job->failed(Object(InvalidArgumentException))
#16 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(499): Illuminate\\Queue\\Jobs\\Job->fail(Object(InvalidArgumentException))
#17 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(459): Illuminate\\Queue\\Worker->failJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(InvalidArgumentException))
#18 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(383): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1, Object(InvalidArgumentException))
#19 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(360): Illuminate\\Queue\\Worker->handleJobException('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions), Object(InvalidArgumentException))
#20 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#21 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#22 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#23 /var/www/backend/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#24 /var/www/backend/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#25 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#26 /var/www/backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#27 /var/www/backend/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 /var/www/backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#29 /var/www/backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#30 /var/www/backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#31 /var/www/backend/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#32 /var/www/backend/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#33 /var/www/backend/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#34 /var/www/backend/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /var/www/backend/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /var/www/backend/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 /var/www/backend/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /var/www/backend/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 {main}
"} 
```

**Comment by fletch3555** [comment]
You're not populating the `$tenant` member on your notification class.  Try getting the current tenant in the constructor and store it there.  Something like:

```
$this->tenant = Tenancy::getTenant();
```

Once it's set, it won't be null, and it'll get caught and returned by the first conditional in your identification method.

**Comment by albertosgz** [comment]
I just tried, but the user is not populated.

The output for the log ' logger('[SendUserCreatedNotification::__construct] 1 ' . $user);'  is still `[2020-07-20 06:52:33] local.DEBUG: [SendUserCreatedNotification::__construct] 1[]`

**Comment by ArlonAntonius** [comment]
Hi there @albertosgz,

The `Database Connection [tenant] not configured` error occurs only when something is trying to access the `tenant` connection before it's available (like @fletch3555 stated earlier). In the example code you have provided to us we saw a few things:
- Your Job class has a `tenant` variable defined, which is always `null` / `undefined`

We expect that because this is always being the listed value, it would end up with Tenancy not identifying a tenant based on the logic you implemented in the `tenantIdentificationByQueue` method. We would recommend you to remove the specified variable and try to run it again.

I hope this helps, if not, feel free to mention me on our Discord Server where I'll try to help you in a more detailed way with this issue.

**Comment by RowlandOti** [comment]
Might be useful to switch to the tenats connection using:

`event(new Switched(Tenancy::getTenant())));`

This way the correct tenant database is used.

**Comment by RowlandOti** [comment]
It will help to switch to the tenant connection by using: 

`event(new Switched(Tenancy::getTenant())));`

**Comment by fletch3555** [comment]
@RowlandOti that won't work since `Tenancy::getTenant()` will only return an identified tenant, which means the database will connection and everything else will have already been setup.  At best, it's a redundant step.  At worst, it throws an exception

**Comment by ArlonAntonius** [comment]
Closing this issue due to inactivity.

If you feel like your issue has not been properly addressed yet, or if you still need more information, please reopen this issue 😄

If you require help with a different issue, please open a new issue.

You can also find Tenancy related help & resources on:
- [Our Website](https://tenancy.dev/)
- [Our Forums](https://discuss.tenancy.dev/)
- [Our Discord Server](https://tenancy.dev/chat)

**Comment by chWagnr** [comment]
I don't know if it's still current... I got this error while unserializing queued jobs. At this moment there is no tenant set and models can not be restored from database. I wrote a workaround for my tenant dependent jobs:

```php
use Illuminate\Queue\SerializesModels;

trait TenantJobs
{
    use SerializesModels {
        __unserialize as public baseUnserialize;
    }

    public function __unserialize(array $values)
    {
        $tenantId = optional($values['tenant'])->id;
        $tenant = Tenancy::getTenant();
        if ((bool) $tenantId && (!$tenant || $tenant->id !== $tenantId)) {
            Tenancy::setTenant(Tenant::find($tenantId));
        }
        $this->baseUnserialize($values);
    }
}
```

`$values` array contains something like this:
```
[
  "tenant" => Illuminate\Contracts\Database\ModelIdentifier^ {#2557
    +class: "App\Models\Tenant"
    +id: 1
    +relations: []
    +connection: "mysql"
  }
  "timeout" => 115
  "\x00*\x00project" => Illuminate\Contracts\Database\ModelIdentifier^ {#2546
    +class: "App\Models\Project"
    +id: 860
    +relations: []
    +connection: "tenant"
  }
]
```

**Comment by fletch3555** [comment]
> I don't know if it's still current... I got this error while unserializing queued jobs. At this moment there is no tenant set and models can not be restored from database. I wrote a workaround for my tenant dependent jobs:
> 
> ```php
> use Illuminate\Queue\SerializesModels;
> 
> trait TenantJobs
> {
>     use SerializesModels {
>         __unserialize as public baseUnserialize;
>     }
> 
>     public function __unserialize(array $values)
>     {
>         $tenantId = optional($values['tenant'])->id;
>         $tenant = Tenancy::getTenant();
>         if ((bool) $tenantId && (!$tenant || $tenant->id !== $tenantId)) {
>             Tenancy::setTenant(Tenant::find($tenantId));
>         }
>         $this->baseUnserialize($values);
>     }
> }
> ```
> 
> `$values` array contains something like this:
> ```
> [
>   "tenant" => Illuminate\Contracts\Database\ModelIdentifier^ {#2557
>     +class: "App\Models\Tenant"
>     +id: 1
>     +relations: []
>     +connection: "mysql"
>   }
>   "timeout" => 115
>   "\x00*\x00project" => Illuminate\Contracts\Database\ModelIdentifier^ {#2546
>     +class: "App\Models\Project"
>     +id: 860
>     +relations: []
>     +connection: "tenant"
>   }
> ]
> ```
> 
> 

That should all be unnecessary.  You already have a tenant object in your job, so that side is already working. Sounds like you're missing (or have misconfigured) queue identification: https://tenancy.dev/docs/tenancy/1.x/identification-queue

**Comment by chWagnr** [comment]
I forgot to mention that the error occurs when I retry a failed job via artisan.
