### ISSUE TITLE
identification-driver-queue Is not connecting to the tenant database returning null for db keys.

### ISSUE THREAD

**Issue by SaurabhDwi** [tenancy/tenancy#230]
__Description__
I am using tenancy dev for my project and  I am facing issues with the queue handle function to connect to tenant DB.
..

---

__Actual behavior__
Is not resolving the db config for the tenant connection and returning config keys null.

![image](https://user-images.githubusercontent.com/74905553/116272061-358c7180-a79e-11eb-8091-cdadf1597c44.png)

..

__Expected behavior__
It should be connected to the tenant database in the queue job.
![image](https://user-images.githubusercontent.com/74905553/116272168-5359d680-a79e-11eb-903a-dd7c919d2b3f.png)

..

---
__Information__

- tenancy/tenancy version: 1.*
- laravel version: ^7.0
- database driver and version: Mysql, 5.6
- webserver software and version: XAMPP
- php version: 7.3

---

__tenancy.php config__

```php

```

---

__Error log__

```text
#0 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(180): Illuminate\\Database\\Connectors\\ConnectionFactory->parseHosts(Array)
#1 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#2 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(926): call_user_func(Object(Closure))
#3 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(961): Illuminate\\Database\\Connection->getPdo()
#4 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(405): Illuminate\\Database\\Connection->getReadPdo()
#5 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(331): Illuminate\\Database\\Connection->getPdoForSelect(true)
#6 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#7 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#8 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(339): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#9 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2260): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#10 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2248): Illuminate\\Database\\Query\\Builder->runSelect()
#11 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2743): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#12 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2249): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#13 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(548): Illuminate\\Database\\Query\\Builder->get(Array)
#14 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(532): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#15 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#16 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\app\\Jobs\\Tenent\\DisburseAttendancePointJob.php(62): Illuminate\\Database\\Eloquent\\Builder->first()
#17 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Jobs\\Tenent\\DisburseAttendancePointJob->handle()
#18 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#20 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#23 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\Tenent\\DisburseAttendancePointJob))
#24 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Tenent\\DisburseAttendancePointJob))
#25 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\Tenent\\DisburseAttendancePointJob), false)
#27 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\Tenent\\DisburseAttendancePointJob))
#28 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Tenent\\DisburseAttendancePointJob))
#29 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(App\\Jobs\\Tenent\\DisburseAttendancePointJob))
#31 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Jobs\\Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#32 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#33 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(306): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#34 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#35 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#36 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#37 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#38 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#39 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#40 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#41 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#42 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#43 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\symfony\\console\\Command\\Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#44 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#45 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\symfony\\console\\Application.php(920): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\symfony\\console\\Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\symfony\\console\\Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 M:\\hardwork\\htdocs\\mt-projects\\lms\\sms_lms_development\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 {main}
"}
```

**Comment by bkintanar** [comment]
@SaurabhDwi maybe a dumb question, does your code pass through the `tenantIdentificationByQueue` method in your Tenant enabled model?

**Comment by SaurabhDwi** [comment]
Yes, I enabled a tenantIdentificationByQueue method in the Identification model.

![image](https://user-images.githubusercontent.com/74905553/116344408-ccd7e000-a803-11eb-9bf7-9b6d62386101.png)

**Comment by bkintanar** [comment]
@SaurabhDwi that isn't what I asked. did it pass through this code? E.g. try adding a dd inside and run a job if it runs through this code.

**Comment by SaurabhDwi** [comment]
**In step 1: A Job will be saved in the data database with tenant details as suggested by** https://tenancy.dev/docs/tenancy/1.x/identification-queue

At a time of saving job getting these logs in ResolveTenantConnection and job construct

![image](https://user-images.githubusercontent.com/74905553/116346894-c009bb00-a808-11eb-9ef8-f9d67b68980a.png)

**2. On running job by queue worker getting these in tenantIdentificationByQueue, ResolveTenantConnection and job handle function. Check log file for details**
[laravel-2021-04-28.log](https://github.com/tenancy/tenancy/files/6389077/laravel-2021-04-28.log)

**Code In ResolveTenantConnection** 
![image](https://user-images.githubusercontent.com/74905553/116347204-65249380-a809-11eb-9ac5-d589aac1cb71.png)

**Code in tenantIdentificationByQueue**
![image](https://user-images.githubusercontent.com/74905553/116347279-8b4a3380-a809-11eb-8e74-4a788891b835.png)

**Code in queue job**
![image](https://user-images.githubusercontent.com/74905553/116347349-aae15c00-a809-11eb-8a48-35668b3ed5d6.png)

**Comment by bkintanar** [comment]
So it's not setting the right connection in ResolveTenantConnection.

**Comment by SaurabhDwi** [comment]
Yes, It always returning null.

**Comment by bkintanar** [comment]
@SaurabhDwi what's the contents of your dbDetails? can you try logging that?

**Comment by ArlonAntonius** [comment]
Closing this issue due to inactivity.

If you feel like your issue has not been properly addressed yet, or if you still need more information, please reopen this issue 😄

If you require help with a different issue, please open a new issue.

You can also find Tenancy related help & resources on:
- [Our Website](https://tenancy.dev/)
- [Our Forums](https://discuss.tenancy.dev/)
- [Our Discord Server](https://tenancy.dev/chat)
